# Start with the Ubuntu base image
FROM ubuntu:20.04

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Update and install necessary packages
RUN apt-get update && apt-get install -y \
    xfce4 \
    xfce4-goodies \
    tigervnc-standalone-server \
    tigervnc-common \
    firefox \
    wget \
    nano \
    xrdp && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
